### ISSUE TITLE
error after update to angular 17

### ISSUE THREAD

**Issue by ONDEMGE** [MarcHeidingsfelder/angular-unit-test-runner#1]
npm ERR! While resolving: @mh-code/angular-unit-test-runner@1.2.0
npm ERR! Found: @angular/cli@17.0.1
npm ERR! node_modules/@angular/cli
npm ERR!   dev @angular/cli@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cli@"10.0.0 - 15.0.0" from @mh-code/angular-unit-test-runner@1.2.0
npm ERR! node_modules/@mh-code/angular-unit-test-runner
npm ERR!   dev @mh-code/angular-unit-test-runner@"1.2.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/cli@15.0.0
npm ERR! node_modules/@angular/cli
npm ERR!   peer @angular/cli@"10.0.0 - 15.0.0" from @mh-code/angular-unit-test-runner@1.2.0
npm ERR!   node_modules/@mh-code/angular-unit-test-runner
npm ERR!     dev @mh-code/angular-unit-test-runner@"1.2.0" from the root project

**Comment by MarcHeidingsfelder** [comment]
Angular 17 is now supported (Version 1.3.1 or newer) 
(Commit: 190708cd401176dc3fa44eb4f40d5d6fcc1efba7)

**Comment by ONDEMGE** [comment]
Patch versions currently not supported

**Comment by MarcHeidingsfelder** [comment]
New version is available
